spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/greenhand?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  application:
    name: ServiceMonday
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
  redis:
    host: 192.168.1.10
    port: 6379
    timeout: 3000
    jedis:
      pool:
        max-wait: 30000
        min-idle: 0
        max-idle: 20
        max-active: 100
#local:
#   variable:
#rocketmq:
#  consumer:
#    # RocketMQ的请求地址
#    namesrvAddr: 192.168.1.8:9876
#    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
#    groupName: test-demo
#    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
#    instanceName: consumer.demo
#  producer:
#    #发送消息超时时间
#    sendMsgTimeout: 10000
#    #maxMessageSize最大消息限制
#    maxMessageSize: 999999999
#    #消息大小超出配置对消息压缩
#    compressOver: 40000
#  topic: test-demo
#  # 不配置为订阅全部tag,多个行业用 "||" 分隔, 如："0||1||2"
#  tag: "111"
ribbon:
  eureka:
    enabled: false
