##文件名：
#application-test-dev.yml
##文件内容：
#server:
#  port: 8086
#spring:
#  datasource:
#    url: jdbc:mysql://127.0.0.1:3306/greenhand?useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: root
#    password: 123456
#    goods: apple